use super::*;

/// Metadata for any entity.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Meta<Id, T> {
    pub id: Id,
    /// Tags for the entity. Can also be name or title.
    /// - If there's only one tag, it's rendered as a title.
    /// - If the first tag starts with `!`, it's rendered as a title.
    /// - All the rest are rendered as normal tags.
    /// 
    /// Can be used for filtering and sorting.
    /// - The leading `!` or `?` are removed when filtering.
    /// - The leading `!` will come first when sorting, while `?` the last.
    pub tags: Vec<String>,
    /// When the entity was created.
    pub created_at: DateTime<Utc>,
    /// When the entity was last updated.
    pub updated_at: DateTime<Utc>,
    /// Summary generated by LLM.
    pub vibe: Option<Vibe>,
    /// Inner content of the entity.
    pub inner: T,
}

/// Summary generated by LLM.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Vibe {
    /// First line / heuristic (optional metadata, potentially LLM-generated).
    pub title: Option<String>,
    /// Short LLM summary.
    pub summary: Option<String>,
    /// Priority score, 0.0–1.0.
    pub importance: Option<f32>,
    /// Keywords.
    pub keywords: Vec<String>,
}
