use super::*;

/// Metadata for any entity.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Meta<Id, T> {
    pub id: Id,
    pub created_at: DateTime<Utc>,
    pub updated_at: DateTime<Utc>,
    pub vibe: Option<Vibe>,

    pub inner: T,
}

/// Summary generated by LLM.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Vibe {
    /// First line / heuristic (optional metadata, potentially LLM-generated).
    pub title: Option<String>,
    /// Short LLM summary.
    pub summary: Option<String>,
    /// Priority score, 0.0–1.0.
    pub importance: Option<f32>,
    /// Keywords.
    pub keywords: Vec<String>,
}
